name: cobre
batch_size: 16
test_batch_size: 16
val_batch_size: 16
train_set: 0.7
val_set: 0.1
path: /Users/pavelpopov/usman_code/BrainNetworkTransformer/source/conf/dataset/abide.npy
stratified: False
drop_last: True